const actionTypes = {
  CREATE_USER: 'CREATE_USER',
  CREATE_WORDS: 'CREATE_WORDS',
  UPDATE_USER_WORDS_COUNTS: 'UPDATE_USER_WORDS_COUNTS',
  REMOVE_WORD: 'REMOVE_WORD',
  LOGOUT_USER: 'LOGOUT_USER',

  SET_LANGUAGE_NAME: 'SET_LANGUAGE_NAME',
  SET_LANGUAGES: 'SET_LANGUAGES',

  SET_TRANSLATIONS: 'SET_TRANSLATIONS',
}

export default actionTypes
