# name: Deploy Site on push
# on:
#   push:
#     branches:
#       - main
# jobs:
#   web-deploy:
#     name: Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: Get the latest code
#       uses: actions/checkout@v2.3.2
#     - uses: actions/setup-node@master 
#     - name: deploy
#       uses: fifsky/ssh-action@master
#       with:
#         command: ${{ secrets.WORDS_APP_REDIRECT_AND_RUN_SH_FILE }}
#         host: ${{ secrets.WORDS_APP_SSH_SERVER }}
#         user: ${{ secrets.WORDS_APP_SSH_USER }}
#         pass: ${{ secrets.WORDS_APP_SSH_PASSWORD }}
    
